# Generated by Django 5.2.17 on 2026-09-29 11:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('story', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField()),
                ('opening_hours', models.CharField(blank=True, max_length=240)),
                ('primary_color', models.CharField(default='#C8532D', max_length=7)),
                ('accent_color', models.CharField(default='#E8C17A', max_length=7)),
                ('logo', models.ImageField(blank=True, upload_to='dealers/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_vehicle_id', models.UUIDField(unique=True)),
                ('dealer_id', models.UUIDField()),
                ('source_version', models.PositiveBigIntegerField()),
                ('dealer_data', models.JSONField()),
                ('visibility', models.CharField(choices=[('pending_review', 'Pending review'), ('public', 'Public'), ('hidden', 'Hidden'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending_review', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=180)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('transmission', models.CharField(max_length=40)),
                ('fuel_type', models.CharField(max_length=40)),
                ('condition', models.CharField(help_text='Dealer-provided condition', max_length=80)),
                ('location', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('known_issues', models.TextField(blank=True)),
                ('seller_history', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='draft', max_length=16)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=16)),
                ('is_featured', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='dealers.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('inquiry', 'General inquiry'), ('viewing', 'Viewing / test drive'), ('offer', 'Offer')], max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('closed', 'Closed')], default='new', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True)),
                ('preferred_at', models.DateTimeField(blank=True, null=True)),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('staff_note', models.TextField(blank=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requests', to='dealers.dealer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_requests', to='dealers.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='vehicles/%Y/%m/')),
                ('alt_text', models.CharField(max_length=180)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dealers.vehicle')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='dealers.dealer')),
            ],
            options={
                'indexes': [models.Index(fields=['dealer', '-created_at'], name='dealers_aud_dealer__fe7db9_idx'), models.Index(fields=['entity_type', 'entity_id'], name='dealers_aud_entity__56a072_idx')],
            },
        ),
        migrations.CreateModel(
            name='DealerDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='dealers.dealer')),
            ],
            options={
                'indexes': [models.Index(fields=['hostname'], name='dealers_dea_hostnam_3cb708_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('sales', 'Sales'), ('viewer', 'Viewer')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dealers.dealer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dealer', 'user'), name='unique_dealer_member')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=32)),
                ('aggregate_id', models.UUIDField()),
                ('aggregate_version', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='dealers.dealer')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='dealers_out_status_c97242_idx')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_type', 'aggregate_id', 'aggregate_version', 'event_type'), name='unique_versioned_event')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['dealer', 'publication_status', 'availability'], name='dealers_veh_dealer__2f778e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['dealer', '-created_at'], name='dealers_veh_dealer__9508b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('dealer', 'slug'), name='unique_vehicle_slug_per_dealer'),
        ),
        migrations.AddIndex(
            model_name='buyerrequest',
            index=models.Index(fields=['dealer', 'status', '-created_at'], name='dealers_buy_dealer__1a4c5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleimage',
            constraint=models.UniqueConstraint(fields=('vehicle', 'position'), name='unique_vehicle_image_position'),
        ),
    ]
