# Generated by Django 5.2.17 on 2026-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerrequest',
            name='appointment_outcome',
            field=models.CharField(choices=[('not_set', 'Not set'), ('attended', 'Attended'), ('no_show', 'No-show'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='not_set', max_length=20),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='counter_offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='offer_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending review'), ('countered', 'Counteroffer sent'), ('accepted', 'Offer accepted — sale not completed'), ('declined', 'Declined')], default='not_applicable', max_length=24),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
