# Generated by Django 5.2.17 on 2026-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_buyerrequest_appointment_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='accent_color',
            field=models.CharField(default='#B8C8B6', max_length=7),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='primary_color',
            field=models.CharField(default='#416B61', max_length=7),
        ),
    ]
